<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Krishna Vikram">
<meta name="author" content="Atul Jayapal*">
<meta name="author" content="Shalini Pillai">
<meta name="author" content="Sheeba Rebecca Isaac">
<meta name="author" content="Mini V">
<meta name="dcterms.date" content="2025-06-20">
<meta name="keywords" content="biochar, okra, nutrient uptake, soil fertility, coastal sandy loam, Kerala">

<title>Biochar for Enhancing Yield, Nutrient Uptake, and Soil Fertility in Okra – JOSTA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/cover.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0626ff4d7a71b55c8707dcae1d04a9b6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-e25cc82807363e79c52e96bc8b7855f1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d53daca99197445b18154044ae73bc11.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-278209a1080c747a323a5f6c0262cc7d.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Biochar for Enhancing Yield, Nutrient Uptake, and Soil Fertility in Okra – JOSTA">
<meta property="og:description" content="The beneficial role of biochar in improving soil fertility is well known, but the optimal application rate in sandy loam soils remains unclear. To address this gap, a field experiment was conducted in 2023 on the coastal sandy loam soils of Kayamkulam, Kerala, to assess the impact of different biochar rates on okra yield, nutrient uptake, and soil fertility. The study followed a randomized block design with nine treatments: various combinations of biochar (5 and 10 t ha\(^{-1}\)), farmyard manure (5 and 20 t ha\(^{-1}\)), and two nutrient levels (75% and 100% RDF). Results revealed that the application of biochar at 10 t ha\(^{-1}\) along with the recommended nutrient dose (110:35:70 kg N:P\(_2\)O\(_5\):K\(_2\)O ha\(^{-1}\)) significantly improved okra yield and nutrient uptake while enhancing soil fertility. The findings highlight the potential of biochar as a soil conditioner and underscore the importance of application rate for achieving optimal benefits.">
<meta property="og:image" content="https://www.jostapubs.com/volume1/AGRON/images/cover.jpg">
<meta property="og:site_name" content="JOSTA">
<meta property="og:image:alt" content="JOSTA Volume 1 Cover">
<meta name="twitter:title" content="Biochar for Enhancing Yield, Nutrient Uptake, and Soil Fertility in Okra – JOSTA">
<meta name="twitter:description" content="The beneficial role of biochar in improving soil fertility is well known, but the optimal application rate in sandy loam soils remains unclear. To address this gap, a field experiment was conducted in 2023 on the coastal sandy loam soils of Kayamkulam, Kerala, to assess the impact of different biochar rates on okra yield, nutrient uptake, and soil fertility. The study followed a randomized block design with nine treatments: various combinations of biochar (5 and 10 t ha\(^{-1}\)), farmyard manure (5 and 20 t ha\(^{-1}\)), and two nutrient levels (75% and 100% RDF). Results revealed that the application of biochar at 10 t ha\(^{-1}\) along with the recommended nutrient dose (110:35:70 kg N:P\(_2\)O\(_5\):K\(_2\)O ha\(^{-1}\)) significantly improved okra yield and nutrient uptake while enhancing soil fertility. The findings highlight the potential of biochar as a soil conditioner and underscore the importance of application rate for achieving optimal benefits.">
<meta name="twitter:image" content="https://www.jostapubs.com/volume1/AGRON/images/papayalogo.png">
<meta name="twitter:image:alt" content="JOSTA Journal">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Biochar for Enhancing Yield, Nutrient Uptake, and Soil Fertility in Okra</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/sidebarcover.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Submit Articles</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../submit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submit article</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../authorguide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Article submission</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../peerReview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Peer Review Policy</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../published.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Latest Articles</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Volumes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Volume 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Issues</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../volume1issue1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Issue 1</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../editorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Editorial Board</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../editorialsection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Editorial Sections</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Report a Problem</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contact.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contact Us</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#materials-and-methods" id="toc-materials-and-methods" class="nav-link" data-scroll-target="#materials-and-methods"><span class="header-section-number">2</span> Materials and methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3</span> Results</a>
  <ul class="collapse">
  <li><a href="#yield-and-plant-performance" id="toc-yield-and-plant-performance" class="nav-link" data-scroll-target="#yield-and-plant-performance"><span class="header-section-number">3.1</span> Yield and plant performance</a></li>
  <li><a href="#nutrient-uptake" id="toc-nutrient-uptake" class="nav-link" data-scroll-target="#nutrient-uptake"><span class="header-section-number">3.2</span> Nutrient uptake</a></li>
  <li><a href="#soil-properties" id="toc-soil-properties" class="nav-link" data-scroll-target="#soil-properties"><span class="header-section-number">3.3</span> Soil properties</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">4</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#yield-attributes" id="toc-yield-attributes" class="nav-link" data-scroll-target="#yield-attributes"><span class="header-section-number">4.1</span> Yield attributes</a></li>
  <li><a href="#nutrient-uptake-1" id="toc-nutrient-uptake-1" class="nav-link" data-scroll-target="#nutrient-uptake-1"><span class="header-section-number">4.2</span> Nutrient uptake</a></li>
  </ul></li>
  <li><a href="#soil-attributes" id="toc-soil-attributes" class="nav-link" data-scroll-target="#soil-attributes"><span class="header-section-number">5</span> Soil attributes</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biochar for Enhancing Yield, Nutrient Uptake, and Soil Fertility in Okra</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Orignal-Article</div>
    <div class="quarto-category">Plant-Science</div>
    <div class="quarto-category">Crops</div>
    <div class="quarto-category">Agronomy</div>
  </div>
  </div>


<div class="quarto-title-meta-author column-body">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Krishna Vikram <a href="mailto:krishnavikram1996@gmail.com" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Kerala Agricultural University
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://coavellayani.kau.in/people/atul-jayapal-dr-0">Atul Jayapal*</a> <a href="mailto:atul.j@kau.in" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Kerala Agricultural University
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://kau.in/people/shalini-pillai-p-dr">Shalini Pillai</a> <a href="mailto:shalini.pillai@kau.in" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Kerala Agricultural University
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://rarskum.kau.in/people/dr-sheeba-rebecca-isaac">Sheeba Rebecca Isaac</a> <a href="mailto:sheeba.issac@kau.in" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Kerala Agricultural University
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://kau.in/people/dr-mini-v">Mini V</a> <a href="mailto:mini.vilas@kau.in" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Kerala Agricultural University
          </p>
      </div>
  </div>

<div class="quarto-title-meta column-body">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 20, 2025</p>
    </div>
  </div>
  
    
    <div>
    <div class="quarto-title-meta-heading">Doi</div>
    <div class="quarto-title-meta-contents">
      <p class="doi">
        <a href="https://doi.org/10.5281/zenodo.15706907">10.5281/zenodo.15706907</a>
      </p>
    </div>
  </div>
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>The beneficial role of biochar in improving soil fertility is well known, but the optimal application rate in sandy loam soils remains unclear. To address this gap, a field experiment was conducted in 2023 on the coastal sandy loam soils of Kayamkulam, Kerala, to assess the impact of different biochar rates on okra yield, nutrient uptake, and soil fertility. The study followed a randomized block design with nine treatments: various combinations of biochar (5 and 10 t ha<span class="math inline">\(^{-1}\)</span>), farmyard manure (5 and 20 t ha<span class="math inline">\(^{-1}\)</span>), and two nutrient levels (75% and 100% RDF). Results revealed that the application of biochar at 10 t ha<span class="math inline">\(^{-1}\)</span> along with the recommended nutrient dose (110:35:70 kg N:P<span class="math inline">\(_2\)</span>O<span class="math inline">\(_5\)</span>:K<span class="math inline">\(_2\)</span>O ha<span class="math inline">\(^{-1}\)</span>) significantly improved okra yield and nutrient uptake while enhancing soil fertility. The findings highlight the potential of biochar as a soil conditioner and underscore the importance of application rate for achieving optimal benefits.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>biochar, okra, nutrient uptake, soil fertility, coastal sandy loam, Kerala</p>
  </div>
</div>

</header>


<p>[<a href="https://doi.org/10.5281/zenodo.15706907"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.15706907.svg" class="img-fluid" alt="DOI"></a> <img src="https://img.shields.io/badge/open--access-yes-brightgreen.svg" class="img-fluid" alt="Open Access"> <img src="https://img.shields.io/badge/status-peer--reviewed-brightgreen.png" class="img-fluid" alt="Status"></p>
<div style="display: flex; flex-wrap: wrap; gap: 1rem; align-items: center; margin-top: 1rem;">
<!-- Download PDF Button -->
<p><a href="pdf/JOSTA615202501736.pdf" download="" class="download-btn"> <i class="bi bi-file-earmark-pdf-fill"></i> Download PDF </a></p>
<!-- Copy Citation Button -->
<button id="copy-btn" onclick="copyCitation()" class="copy-btn">
<p>📋 Copy Citation <span id="tooltip">Citation copied!</span></p>
</button>
</div>
<!-- Hidden Citation Text -->
<p><span id="citation-text" style="display: none;">Vikram, K., Jayapal, A., Pillai, S., Isaac, S. R., &amp; Mini V. (2025). Biochar for Enhancing Yield, Nutrient Uptake, and Soil Fertility in Okra. Journal of Sustainable Technology in Agriculture, 1(1). https://doi.org/10.5281/zenodo.15706907</span></p>
<!-- JavaScript -->
<script>
  function copyCitation() {
    const citation = document.getElementById("citation-text").innerText;
    navigator.clipboard.writeText(citation);
    
    const tooltip = document.getElementById("tooltip");
    tooltip.style.visibility = "visible";
    tooltip.style.opacity = "1";
    
    setTimeout(() => {
      tooltip.style.visibility = "hidden";
      tooltip.style.opacity = "0";
    }, 2000);
  }
</script>
<!-- CSS Styling -->
<style>
.download-btn {
  display: inline-flex;
  align-items: center;
  border: 2px solid #28a745;
  background-color: transparent;
  color: #28a745;
  padding: 8px 14px;
  border-radius: 6px;
  font-weight: 500;
  text-decoration: none;
  transition: all 0.3s ease;
}
.download-btn:hover {
  background-color: #28a745;
  color: white;
}
.download-btn i {
  margin-right: 6px;
}

.copy-btn {
  font-size: 0.9rem;
  padding: 8px 14px;
  border: 1px solid black;
  background-color: white;
  color: black;
  border-radius: 6px;
  cursor: pointer;
  position: relative;
}
.copy-btn #tooltip {
  visibility: hidden;
  background-color: black;
  color: #fff;
  text-align: center;
  border-radius: 4px;
  padding: 2px 6px;
  position: absolute;
  z-index: 1;
  bottom: 120%;
  left: 50%;
  transform: translateX(-50%);
  font-size: 0.75rem;
  opacity: 0;
  transition: opacity 0.3s;
}
</style>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>In India, the agricultural waste generated by crops is significantly higher than in many other countries. Due to the lack of suitable technologies for effective disposal, farmers often resort to burning the crop residues as a quick and convenient method to clear fields. According to <span class="citation" data-cites="singh2014">Singh and Kaskaoutis (<a href="#ref-singh2014" role="doc-biblioref">2014</a>)</span>, about 43% of the total crop stubbles produced in India is burnt in-situ, contributing substantially to air pollution. One promising solution to mitigate the environmental impact of crop residue burning is the conversion of crop residues into biochar, a carbon rich material produced through pyrolysis. <span class="citation" data-cites="punnoose2015article">Punnoose and Anitha (<a href="#ref-punnoose2015article" role="doc-biblioref">2015</a>)</span> has reported that biomass possesses several beneficial physical properties including low bulk density, high porosity, and higher water holding capacity. When applied to soil, these properties make biochar, an effective soil conditioner, enhancing both water and nutrient retention in soil and improves the crop yield. In Kerala, tender coconut husk is a prominent form of agricultural waste which requires efficient and ecofriendly disposal methods. Although, a portion of this agricultural waste is currently utilized through composting or as mulch in coconut gardens, these practices are insufficient relative to the large volume of waste produced. The dried tender coconut husk holds significant potential for conversion into biochar, which can then be recycled back into agricultural use to boost soil productivity. The Onattukara tract spread over three districts of Kerala (Alappuzha, Kollam and Pathanamthitta) presents a unique challenge due to its coarse textured, sandy loam soils with inherently low nutrient status. This type of soil is prone to nutrient leaching, especially during rainfall, rendering the applied fertilizers as less effective. Given biochar’s ability to improve soil moisture retention and reduce nutrient leaching, it represents a promising amendment for such type of soils. Therefore, a study was conducted to evaluate the potential of tender coconut husk biochar as a soil conditioner for okra cultivation in the sandy loam soils of Onattukara region.</p>
</section>
<section id="materials-and-methods" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="materials-and-methods"><span class="header-section-number">2</span> Materials and methods</h2>
<p>A field experiment was conducted during the summer of 2023 in the wetlands of the Instructional Farm attached to Onattukara Regional Agricultural Research Station, Kayamkulam, Kerala. The research station is situated at 9.177° North latitude and 76.517° East longitude and at an altitude of 3.05 m above mean sea level. The treatments were laid out in randomized block design comprising of eight treatment combinations of biochar along with two levels of recommended dose of nutrients for okra along with a control and were replicated thrice. The treatments were t1 (biochar @ <span class="math inline">\(5\ \text{t ha}^{-1}\)</span> + 100% RDF)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, t2 (biochar @ <span class="math inline">\(10\ \text{t ha}^{-1}\)</span> + 100% RDF), t3 (biochar @ <span class="math inline">\(5\ \text{t ha}^{-1}\)</span> + <span class="math inline">\(5\ \text{t ha}^{-1}\)</span> FYM + 100% RDF)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, t4 (biochar @ <span class="math inline">\(10\ \text{t ha}^{-1}\)</span> + <span class="math inline">\(5\ \text{t ha}^{-1}\)</span> FYM + 100% RDF), t5 (biochar @ <span class="math inline">\(5\ \text{t ha}^{-1}\)</span> + 75% RDF), t6 (biochar @ <span class="math inline">\(10\ \text{t ha}^{-1}\)</span> + 75% RDF), t7 (biochar @ <span class="math inline">\(5\ \text{t ha}^{-1}\)</span> + <span class="math inline">\(5\ \text{t ha}^{-1}\)</span> FYM + 75% RDF), t8 (biochar @ <span class="math inline">\(10\ \text{t ha}^{-1}\)</span> + <span class="math inline">\(5\ \text{t ha}^{-1}\)</span> FYM + 75% RDF), and t9 (<span class="citation" data-cites="kau2016">KAU POP (<a href="#ref-kau2016" role="doc-biblioref">2016</a>)</span>-<span class="math inline">\(20\ \text{t ha}^{-1}\)</span> FYM + 100% RDF).</p>
<p>Prior to sowing, the experimental area was cleared of stubbles and clods were broken thoroughly. Dolomite was applied uniformly at the rate of 1 t ha<span class="math inline">\(^{-1}\)</span> and was incorporated in soil during primary tillage. The field was laid out as per the treatment design. After the layout, biochar and farmyard manure, along with half N, full P and full K of chemical fertilizers were applied in soil as per the treatments just before sowing. The remaining N was given in soil at one month after sowing along with intercultural operations and earthing up. The seeds of okra var. Arka Anamika were sown in lines in the main field at a spacing of 60 cm × 30 cm. The crop was sown during the last week of January 2023. After sowing, uniform population was maintained by thinning and gap filling. Five random plants from each net plot were selected and tagged as observational plants for recording observations.</p>
<p>The number of days taken for the first flower to open was noted and the mean was worked out. To find the number of fruits per plant, the fruits obtained from different harvests from each of the five observational plants were recorded separately and the average was worked out. The length of the fruits, from the tip of the fruit to the stalk end, was measured from the observational plants and the average was calculated and expressed in cm. The weight of the fruits harvested from each of the observational plants was recorded after each harvest. After the final harvest, the total weight of fruits obtained from the observational plants at different harvests were worked out, averaged and expressed in kilograms for fruit yield per plant. The weight of fruits from each plot excluding the border plants was recorded after each harvest and summed at the end of the cropping season to compute the yield in terms of kg per plot and was converted into t ha<span class="math inline">\(^{-1}\)</span>.</p>
<p>The harvest index was calculated using the following formula suggested by Donald and Hamblin (1976). It was calculated by dividing the economic yield with biological yield of the plant. Sample plants collected from each plot were chopped into small pieces and were sun dried. After the initial drying, the samples were dried in oven to attain constant weight. The samples were then ground to pass through a 0.5 mm mesh and the required quantity of samples were digested and used for nutrient analysis following standard procedures. The nutrient uptake was calculated and expressed in kg ha<span class="math inline">\(^{-1}\)</span> according to <a href="#eq-eq1" class="quarto-xref">Equation&nbsp;1</a>.</p>
<p><span id="eq-eq1"><span class="math display">\[\text{Nutrient uptake (kg ha}^{-1}\text{)} = \frac{\text{Nutrient content (\%)} \times \text{Dry matter production (kg ha}^{-1}\text{)}}{100} \tag{1}\]</span></span></p>
<p>The composite soil samples from the field before the experiment and from each plot after the experiment were collected, air dried, powdered and passed through a 2 mm sieve and analysed for physico-chemical properties of the soil (<a href="#tbl-tbl1" class="quarto-xref">Table&nbsp;1</a>). The soil samples passed through 0.2 mm sieve were used for organic carbon estimation. Values represented in <a href="#tbl-tbl1" class="quarto-xref">Table&nbsp;1</a> are initial soil values.</p>
<div id="tbl-tbl1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tbl1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Standard analytical procedures used for the soil analysis
</figcaption>
<div aria-describedby="tbl-tbl1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Sl. No.</th>
<th>Characters</th>
<th>Values</th>
<th>Methods</th>
<th>Reference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Water holding capacity (%)</td>
<td>10.47</td>
<td>Core sampling</td>
<td><span class="citation" data-cites="black1965">Black (<a href="#ref-black1965" role="doc-biblioref">1965</a>)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td>Bulk density (<span class="math inline">\(\text{Mg}\ \text{m}^{-3}\)</span>)</td>
<td>1.61</td>
<td>Undisturbed core sample</td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td>Soil reaction (pH)</td>
<td>5.38</td>
<td>pH meter (1:2.5 soil water ratio)</td>
<td><span class="citation" data-cites="jackson1958">Jackson (<a href="#ref-jackson1958" role="doc-biblioref">1958</a>)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td>EC (<span class="math inline">\(\text{dS}\ \text{m}^{-1}\)</span>)</td>
<td>0.01</td>
<td>Conductivity meter (1:2.5 soil water ratio)</td>
<td><span class="citation" data-cites="jackson1958">Jackson (<a href="#ref-jackson1958" role="doc-biblioref">1958</a>)</span></td>
</tr>
<tr class="odd">
<td>5</td>
<td>CEC (<span class="math inline">\(\text{cmol}(+)\ \text{kg}^{-1}\)</span>)</td>
<td>2.28</td>
<td>Ammonium saturation with neutral normal ammonium acetate and distillation</td>
<td><span class="citation" data-cites="jackson1973">Jackson (<a href="#ref-jackson1973" role="doc-biblioref">1973</a>)</span></td>
</tr>
<tr class="even">
<td>6</td>
<td>Organic carbon (%)</td>
<td>0.53</td>
<td>Walkley and Black rapid titration method</td>
<td><span class="citation" data-cites="walkley1934">Walkley and Black (<a href="#ref-walkley1934" role="doc-biblioref">1934</a>)</span></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Available N (<span class="math inline">\(\text{kg}\ \text{ha}^{-1}\)</span>)</td>
<td>200.7</td>
<td>Alkaline permanganate method</td>
<td><span class="citation" data-cites="subbiah1956">Subbiah and Asija (<a href="#ref-subbiah1956" role="doc-biblioref">1956</a>)</span></td>
</tr>
<tr class="even">
<td>8</td>
<td>Available P (<span class="math inline">\(\text{kg}\ \text{ha}^{-1}\)</span>)</td>
<td>90.27</td>
<td>Bray No.&nbsp;1 extraction and spectrophotometric estimation</td>
<td><span class="citation" data-cites="jackson1973">Jackson (<a href="#ref-jackson1973" role="doc-biblioref">1973</a>)</span></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Available K (<span class="math inline">\(\text{kg}\ \text{ha}^{-1}\)</span>)</td>
<td>177.18</td>
<td>NH₄OAc extraction and flame photometry</td>
<td><span class="citation" data-cites="jackson1958">Jackson (<a href="#ref-jackson1958" role="doc-biblioref">1958</a>)</span></td>
</tr>
<tr class="even">
<td>10</td>
<td>Exchangeable Ca (<span class="math inline">\(\text{mg}\ \text{ha}^{-1}\)</span>)</td>
<td>169.26</td>
<td>NH₄OAc extraction and AAS estimation</td>
<td><span class="citation" data-cites="hesse1971">Hesse (<a href="#ref-hesse1971" role="doc-biblioref">1971</a>)</span></td>
</tr>
<tr class="odd">
<td></td>
<td>Exchangeable Mg (<span class="math inline">\(\text{mg}\ \text{ha}^{-1}\)</span>)</td>
<td>53.6</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>11</td>
<td>Available S (<span class="math inline">\(\text{mg}\ \text{ha}^{-1}\)</span>)</td>
<td>2.71</td>
<td>CaCl₂ extraction and spectrophotometric estimation</td>
<td><span class="citation" data-cites="chesnin1950">Chesnin and Yien (<a href="#ref-chesnin1950" role="doc-biblioref">1950</a>)</span></td>
</tr>
<tr class="odd">
<td>12</td>
<td>Available Fe (<span class="math inline">\(\text{mg}\ \text{kg}^{-1}\)</span>)</td>
<td>14.74</td>
<td>DTPA extraction and AAS estimation</td>
<td><span class="citation" data-cites="lindsay1978">Lindsay and Norvell (<a href="#ref-lindsay1978" role="doc-biblioref">1978</a>)</span></td>
</tr>
<tr class="even">
<td></td>
<td>Available Mn (<span class="math inline">\(\text{mg}\ \text{kg}^{-1}\)</span>)</td>
<td>3.44</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Available Cu (<span class="math inline">\(\text{mg}\ \text{kg}^{-1}\)</span>)</td>
<td>1.31</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Available Zn (<span class="math inline">\(\text{mg}\ \text{kg}^{-1}\)</span>)</td>
<td>3.44</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td>Available B (<span class="math inline">\(\text{mg}\ \text{kg}^{-1}\)</span>)</td>
<td>0.59</td>
<td>Hot water extraction and azomethane-H spectrophotometric estimation</td>
<td><span class="citation" data-cites="hesse1971">Hesse (<a href="#ref-hesse1971" role="doc-biblioref">1971</a>)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="results" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="results"><span class="header-section-number">3</span> Results</h2>
<section id="yield-and-plant-performance" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="yield-and-plant-performance"><span class="header-section-number">3.1</span> Yield and plant performance</h3>
<p>The application of biochar significantly influenced certain yield traits of okra. Days to flowering ranged between 35 and 37 days after sowing (DAS) across all treatments, but the differences were not statistically significant. Similarly, the number of fruits per plant and fruit length did not differ significantly among treatments. However, fruit yield per plant was significantly affected by biochar application (<a href="#tbl-tbl2" class="quarto-xref">Table&nbsp;2</a>). Treatment t4 resulted in the highest fruit yield per plant (<span class="math inline">\(544.93\ \text{g}\)</span>) and was statistically at par with t3 (<span class="math inline">\(537.74\ \text{g}\)</span>), while the lowest was recorded in t9 (<span class="math inline">\(380.24\ \text{g}\)</span>). Yield per hectare followed a similar trend, with t4 yielding <span class="math inline">\(15.71\ \text{t ha}^{-1}\)</span> and was found to be on par with t3 (<span class="math inline">\(14.07\ \text{t ha}^{-1}\)</span>), and the lowest yield observed in t9 (<span class="math inline">\(7.65\ \text{t ha}^{-1}\)</span>). The harvest index was also positively influenced, with t3 registering the highest value (<span class="math inline">\(0.81\)</span>), which was statistically similar to t4 (<span class="math inline">\(0.81\)</span>), t2 (<span class="math inline">\(0.79\)</span>), t1 (<span class="math inline">\(0.79\)</span>), and t8 (<span class="math inline">\(0.77\)</span>).</p>
</section>
<section id="nutrient-uptake" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="nutrient-uptake"><span class="header-section-number">3.2</span> Nutrient uptake</h3>
<p>The nutrient uptake of okra plants varied across treatments. Nitrogen uptake was significantly higher in t4 (<span class="math inline">\(101.35\ \text{kg ha}^{-1}\)</span>), which was on par with t3, t2, t6, and t5. The lowest N uptake (<span class="math inline">\(74.78\ \text{kg ha}^{-1}\)</span>) was recorded in t9. Phosphorus uptake was highest in t7 (<span class="math inline">\(24.76\ \text{kg ha}^{-1}\)</span>), statistically similar to t8, t6, t5, and t3, while t2 had the lowest (<span class="math inline">\(14.90\ \text{kg ha}^{-1}\)</span>). Potassium uptake was not significantly affected by any treatment. For calcium, t6 showed the highest uptake (<span class="math inline">\(64.94\ \text{kg ha}^{-1}\)</span>), comparable to t3, t7, and t4. Magnesium uptake was also significantly influenced, with t4 showing the highest uptake (<span class="math inline">\(20.47\ \text{kg ha}^{-1}\)</span>), on par with t3, t6, and t8. Sulphur uptake did not differ significantly across treatments. Copper uptake was highest in t1 (<span class="math inline">\(1.82\ \text{kg ha}^{-1}\)</span>), followed closely by t3 (<span class="math inline">\(1.73\ \text{kg ha}^{-1}\)</span>), while the lowest was in t6 (<span class="math inline">\(0.89\ \text{kg ha}^{-1}\)</span>). Zinc and boron uptakes were not significantly influenced by treatments. Iron uptake was significantly higher in t6 (<span class="math inline">\(0.96\ \text{kg ha}^{-1}\)</span>), which was at par with t1 and t3. Manganese uptake was highest in t8 (<span class="math inline">\(1.69\ \text{kg ha}^{-1}\)</span>), statistically similar to t7, t4, and t2.</p>
</section>
<section id="soil-properties" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="soil-properties"><span class="header-section-number">3.3</span> Soil properties</h3>
<p>Post-harvest soil analysis revealed that biochar application significantly influenced several soil physico-chemical parameters. Water holding capacity was significantly higher in t4 (<span class="math inline">\(33.87\%\)</span>), followed by t8, t3, t2, and t7. Bulk density was lowest in t8 (<span class="math inline">\(1.21\ \text{Mg m}^{-3}\)</span>), while t9 recorded the highest (<span class="math inline">\(1.30\ \text{Mg m}^{-3}\)</span>). No significant differences were found in soil pH, electrical conductivity (EC), or cation exchange capacity (CEC). Organic carbon content increased significantly with biochar application, highest in t4 (<span class="math inline">\(1.29\%\)</span>), and statistically comparable to t8, t3, t2, t7, t1, and t6. Available nitrogen content also improved, with t4 (<span class="math inline">\(209.07\ \text{kg ha}^{-1}\)</span>) showing significantly higher values, followed by t3, t8, and t7. However, the availability of phosphorus, potassium, calcium, magnesium, sulphur, copper, zinc, iron, boron, and manganese in the soil was not significantly affected by the treatments.</p>
<div id="tbl-tbl2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tbl2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Effect of treatments on the yield attributes and yield of okra
</figcaption>
<div aria-describedby="tbl-tbl2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Treatment</th>
<th>Days to Flowering</th>
<th>No.&nbsp;of Fruits/Plant</th>
<th>Fruit Length (cm)</th>
<th>Fruit Yield/Plant (g)</th>
<th>Fruit Yield (<span class="math inline">\(\text{t ha}^{-1}\)</span>)</th>
<th>Harvest Index</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t1</td>
<td>38.67</td>
<td>18.00</td>
<td>15.90</td>
<td>480.30</td>
<td>10.44</td>
<td>0.79</td>
</tr>
<tr class="even">
<td>t2</td>
<td>38.67</td>
<td>18.12</td>
<td>16.07</td>
<td>487.23</td>
<td>12.25</td>
<td>0.79</td>
</tr>
<tr class="odd">
<td>t3</td>
<td>38.44</td>
<td>19.90</td>
<td>16.28</td>
<td>537.74</td>
<td>14.07</td>
<td>0.81</td>
</tr>
<tr class="even">
<td>t4</td>
<td>38.67</td>
<td>20.23</td>
<td>16.34</td>
<td>544.93</td>
<td>15.71</td>
<td>0.81</td>
</tr>
<tr class="odd">
<td>t5</td>
<td>38.67</td>
<td>16.11</td>
<td>15.55</td>
<td>392.85</td>
<td>11.26</td>
<td>0.74</td>
</tr>
<tr class="even">
<td>t6</td>
<td>38.78</td>
<td>16.79</td>
<td>15.74</td>
<td>415.59</td>
<td>11.89</td>
<td>0.76</td>
</tr>
<tr class="odd">
<td>t7</td>
<td>38.89</td>
<td>17.45</td>
<td>15.81</td>
<td>457.61</td>
<td>12.19</td>
<td>0.77</td>
</tr>
<tr class="even">
<td>t8</td>
<td>38.67</td>
<td>17.56</td>
<td>15.85</td>
<td>464.61</td>
<td>13.05</td>
<td>0.77</td>
</tr>
<tr class="odd">
<td>t9</td>
<td>38.67</td>
<td>16.11</td>
<td>15.40</td>
<td>380.24</td>
<td>7.65</td>
<td>0.75</td>
</tr>
<tr class="even">
<td><em>SEm (±)</em></td>
<td>0.14</td>
<td>1.33</td>
<td>0.35</td>
<td>16.81</td>
<td>0.63</td>
<td>0.01</td>
</tr>
<tr class="odd">
<td><em>CD (0.05)</em></td>
<td>NS</td>
<td>NS</td>
<td>NS</td>
<td>50.385</td>
<td>1.890</td>
<td>0.037</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-tbl3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tbl3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Effect of treatments on nutrient uptake of okra (N, P, and K)
</figcaption>
<div aria-describedby="tbl-tbl3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Treatment</th>
<th>N (kg ha<span class="math inline">\(^{-1}\)</span>)</th>
<th>P (kg ha<span class="math inline">\(^{-1}\)</span>)</th>
<th>K (kg ha<span class="math inline">\(^{-1}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t1</td>
<td>87.85</td>
<td>17.07</td>
<td>51.93</td>
</tr>
<tr class="even">
<td>t2</td>
<td>92.90</td>
<td>14.90</td>
<td>49.52</td>
</tr>
<tr class="odd">
<td>t3</td>
<td>95.93</td>
<td>19.60</td>
<td>53.88</td>
</tr>
<tr class="even">
<td>t4</td>
<td>101.35</td>
<td>18.45</td>
<td>46.64</td>
</tr>
<tr class="odd">
<td>t5</td>
<td>91.93</td>
<td>19.98</td>
<td>46.68</td>
</tr>
<tr class="even">
<td>t6</td>
<td>92.70</td>
<td>22.57</td>
<td>55.40</td>
</tr>
<tr class="odd">
<td>t7</td>
<td>88.15</td>
<td>24.76</td>
<td>46.47</td>
</tr>
<tr class="even">
<td>t8</td>
<td>84.43</td>
<td>23.73</td>
<td>50.65</td>
</tr>
<tr class="odd">
<td>t9</td>
<td>74.78</td>
<td>17.87</td>
<td>45.96</td>
</tr>
<tr class="even">
<td><em>SEm (±)</em></td>
<td>4.29</td>
<td>1.86</td>
<td>3.42</td>
</tr>
<tr class="odd">
<td><em>CD (0.05)</em></td>
<td>12.848</td>
<td>5.561</td>
<td>NS</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-tbl4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tbl4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Effect of treatments on uptake of nutrients by okra (all values in kg ha<span class="math inline">\(^{-1}\)</span>)
</figcaption>
<div aria-describedby="tbl-tbl4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Treatment</th>
<th>Ca</th>
<th>Mg</th>
<th>S</th>
<th>Cu</th>
<th>Zn</th>
<th>Fe</th>
<th>B</th>
<th>Mn</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t1</td>
<td>53.28</td>
<td>18.27</td>
<td>3.00</td>
<td>1.82</td>
<td>1.86</td>
<td>0.88</td>
<td>0.30</td>
<td>1.36</td>
</tr>
<tr class="even">
<td>t2</td>
<td>52.78</td>
<td>18.00</td>
<td>3.10</td>
<td>1.70</td>
<td>1.83</td>
<td>0.47</td>
<td>0.34</td>
<td>1.46</td>
</tr>
<tr class="odd">
<td>t3</td>
<td>59.72</td>
<td>19.84</td>
<td>3.06</td>
<td>1.73</td>
<td>1.85</td>
<td>0.82</td>
<td>0.32</td>
<td>1.40</td>
</tr>
<tr class="even">
<td>t4</td>
<td>58.61</td>
<td>20.47</td>
<td>3.14</td>
<td>1.19</td>
<td>1.92</td>
<td>0.44</td>
<td>0.34</td>
<td>1.67</td>
</tr>
<tr class="odd">
<td>t5</td>
<td>54.39</td>
<td>16.54</td>
<td>3.03</td>
<td>0.67</td>
<td>1.92</td>
<td>0.67</td>
<td>0.30</td>
<td>1.42</td>
</tr>
<tr class="even">
<td>t6</td>
<td>64.94</td>
<td>19.61</td>
<td>3.05</td>
<td>0.89</td>
<td>1.85</td>
<td>0.96</td>
<td>0.33</td>
<td>1.61</td>
</tr>
<tr class="odd">
<td>t7</td>
<td>59.38</td>
<td>18.66</td>
<td>2.98</td>
<td>1.09</td>
<td>2.04</td>
<td>0.74</td>
<td>0.31</td>
<td>1.68</td>
</tr>
<tr class="even">
<td>t8</td>
<td>56.25</td>
<td>19.60</td>
<td>3.07</td>
<td>1.34</td>
<td>2.01</td>
<td>0.78</td>
<td>0.33</td>
<td>1.69</td>
</tr>
<tr class="odd">
<td>t9</td>
<td>41.10</td>
<td>18.68</td>
<td>2.98</td>
<td>1.68</td>
<td>1.93</td>
<td>0.78</td>
<td>0.31</td>
<td>1.39</td>
</tr>
<tr class="even">
<td><em>SEm (±)</em></td>
<td>2.21</td>
<td>0.35</td>
<td>0.05</td>
<td>0.04</td>
<td>0.18</td>
<td>0.05</td>
<td>0.02</td>
<td>0.08</td>
</tr>
<tr class="odd">
<td><em>CD (0.05)</em></td>
<td>6.610</td>
<td>1.061</td>
<td>NS</td>
<td>0.111</td>
<td>NS</td>
<td>0.151</td>
<td>NS</td>
<td>0.251</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-tbl5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tbl5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Effect of treatments on soil parameters after harvest of okra
</figcaption>
<div aria-describedby="tbl-tbl5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Treatment</th>
<th>WHC (%)</th>
<th>Bulk Density (Mg m<span class="math inline">\(^{-3}\)</span>)</th>
<th>pH</th>
<th>EC (dS m<span class="math inline">\(^{-1}\)</span>)</th>
<th>CEC (cmol(+) kg<span class="math inline">\(^{-1}\)</span>)</th>
<th>Organic Carbon (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t1</td>
<td>30.78</td>
<td>1.26</td>
<td>5.48</td>
<td>0.03</td>
<td>3.11</td>
<td>1.19</td>
</tr>
<tr class="even">
<td>t2</td>
<td>32.65</td>
<td>1.22</td>
<td>5.78</td>
<td>0.03</td>
<td>3.12</td>
<td>1.23</td>
</tr>
<tr class="odd">
<td>t3</td>
<td>32.73</td>
<td>1.23</td>
<td>5.59</td>
<td>0.02</td>
<td>3.06</td>
<td>1.25</td>
</tr>
<tr class="even">
<td>t4</td>
<td>33.87</td>
<td>1.22</td>
<td>5.87</td>
<td>0.03</td>
<td>3.11</td>
<td>1.29</td>
</tr>
<tr class="odd">
<td>t5</td>
<td>29.45</td>
<td>1.24</td>
<td>5.66</td>
<td>0.02</td>
<td>3.08</td>
<td>1.10</td>
</tr>
<tr class="even">
<td>t6</td>
<td>30.91</td>
<td>1.22</td>
<td>5.76</td>
<td>0.09</td>
<td>3.09</td>
<td>1.17</td>
</tr>
<tr class="odd">
<td>t7</td>
<td>32.61</td>
<td>1.22</td>
<td>5.67</td>
<td>0.04</td>
<td>3.11</td>
<td>1.23</td>
</tr>
<tr class="even">
<td>t8</td>
<td>33.02</td>
<td>1.21</td>
<td>5.84</td>
<td>0.02</td>
<td>3.07</td>
<td>1.26</td>
</tr>
<tr class="odd">
<td>t9</td>
<td>27.52</td>
<td>1.30</td>
<td>5.31</td>
<td>0.03</td>
<td>3.05</td>
<td>0.96</td>
</tr>
<tr class="even">
<td><em>SEm (±)</em></td>
<td>0.57</td>
<td>0.00</td>
<td>0.11</td>
<td>0.03</td>
<td>0.04</td>
<td>0.05</td>
</tr>
<tr class="odd">
<td><em>CD (0.05)</em></td>
<td>1.695</td>
<td>0.008</td>
<td>NS</td>
<td>NS</td>
<td>NS</td>
<td>0.134</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-tbl6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tbl6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Effect of treatments on primary nutrient status of soil after the experiment (all values in kg ha<span class="math inline">\(^{-1}\)</span>)
</figcaption>
<div aria-describedby="tbl-tbl6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Treatment</th>
<th>Available N</th>
<th>Available P</th>
<th>Available K</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t1</td>
<td>188.16</td>
<td>76.91</td>
<td>161.43</td>
</tr>
<tr class="even">
<td>t2</td>
<td>188.16</td>
<td>79.63</td>
<td>152.13</td>
</tr>
<tr class="odd">
<td>t3</td>
<td>196.52</td>
<td>76.36</td>
<td>146.46</td>
</tr>
<tr class="even">
<td>t4</td>
<td>209.07</td>
<td>94.90</td>
<td>172.70</td>
</tr>
<tr class="odd">
<td>t5</td>
<td>163.07</td>
<td>80.72</td>
<td>189.47</td>
</tr>
<tr class="even">
<td>t6</td>
<td>163.07</td>
<td>82.73</td>
<td>159.64</td>
</tr>
<tr class="odd">
<td>t7</td>
<td>196.52</td>
<td>88.00</td>
<td>172.03</td>
</tr>
<tr class="even">
<td>t8</td>
<td>196.52</td>
<td>75.09</td>
<td>173.26</td>
</tr>
<tr class="odd">
<td>t9</td>
<td>183.98</td>
<td>73.63</td>
<td>149.74</td>
</tr>
<tr class="even">
<td><em>SEm (±)</em></td>
<td>6.97</td>
<td>7.08</td>
<td>10.63</td>
</tr>
<tr class="odd">
<td><em>CD (0.05)</em></td>
<td>20.890</td>
<td>NS</td>
<td>NS</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-tbl7" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tbl7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Effect of treatments on secondary and micronutrient status of soil after the experiment (all values in mg kg<span class="math inline">\(^{-1}\)</span>)
</figcaption>
<div aria-describedby="tbl-tbl7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Treatment</th>
<th>Ex.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Ca</th>
<th>Ex. Mg</th>
<th>Available S</th>
<th>Available Cu</th>
<th>Available Zn</th>
<th>Available Fe</th>
<th>Available B</th>
<th>Available Mn</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t1</td>
<td>446.10</td>
<td>83.08</td>
<td>2.53</td>
<td>1.45</td>
<td>2.35</td>
<td>14.72</td>
<td>0.29</td>
<td>3.78</td>
</tr>
<tr class="even">
<td>t2</td>
<td>437.03</td>
<td>87.28</td>
<td>3.19</td>
<td>1.43</td>
<td>2.62</td>
<td>15.42</td>
<td>0.29</td>
<td>3.81</td>
</tr>
<tr class="odd">
<td>t3</td>
<td>426.70</td>
<td>88.68</td>
<td>2.69</td>
<td>1.45</td>
<td>2.64</td>
<td>15.38</td>
<td>0.29</td>
<td>3.95</td>
</tr>
<tr class="even">
<td>t4</td>
<td>403.75</td>
<td>88.19</td>
<td>2.84</td>
<td>1.42</td>
<td>2.40</td>
<td>15.38</td>
<td>0.29</td>
<td>3.74</td>
</tr>
<tr class="odd">
<td>t5</td>
<td>456.83</td>
<td>72.93</td>
<td>2.22</td>
<td>1.33</td>
<td>2.67</td>
<td>15.21</td>
<td>0.28</td>
<td>3.99</td>
</tr>
<tr class="even">
<td>t6</td>
<td>398.10</td>
<td>80.63</td>
<td>2.86</td>
<td>1.34</td>
<td>2.42</td>
<td>15.53</td>
<td>0.27</td>
<td>3.95</td>
</tr>
<tr class="odd">
<td>t7</td>
<td>391.80</td>
<td>89.02</td>
<td>2.82</td>
<td>1.28</td>
<td>2.18</td>
<td>15.14</td>
<td>0.28</td>
<td>3.83</td>
</tr>
<tr class="even">
<td>t8</td>
<td>407.92</td>
<td>89.90</td>
<td>3.06</td>
<td>1.40</td>
<td>2.14</td>
<td>14.82</td>
<td>0.28</td>
<td>3.45</td>
</tr>
<tr class="odd">
<td>t9</td>
<td>376.03</td>
<td>84.69</td>
<td>2.67</td>
<td>1.33</td>
<td>2.63</td>
<td>14.82</td>
<td>0.28</td>
<td>3.47</td>
</tr>
<tr class="even">
<td><em>SEm (±)</em></td>
<td>21.62</td>
<td>4.94</td>
<td>0.19</td>
<td>0.05</td>
<td>0.18</td>
<td>0.46</td>
<td>0.01</td>
<td>0.16</td>
</tr>
<tr class="odd">
<td><em>CD (0.05)</em></td>
<td>NS</td>
<td>NS</td>
<td>NS</td>
<td>NS</td>
<td>NS</td>
<td>NS</td>
<td>NS</td>
<td>NS</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="discussion" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="discussion"><span class="header-section-number">4</span> Discussion</h2>
<section id="yield-attributes" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="yield-attributes"><span class="header-section-number">4.1</span> Yield attributes</h3>
<p>The treatments did not influence the days taken to flower in okra. In general, regardless of the treatments, the okra plants started to flower between 35 DAS and 37 DAS. The number of fruits per plant and length of fruits were not influenced by biochar. However, the fruit yield per plant was significantly improved by the incorporation of biochar. The highest yield per plant was obtained from t4 (<span class="math inline">\(544.93\ \text{g}\)</span>) and was found to be on a par with the treatment t3 (<span class="math inline">\(537.74\ \text{g}\)</span> per plant). There was 35.60 per cent increase over t9. Higher fruit yield per plant was observed for the plants that received biochar and FYM along with 100 per cent recommended dose of fertilizers (RDF). The adsorbing property of biochar in sandy loam soil might have slowed down the release of nutrients from FYM and chemical fertilizers. As the amount of biochar was doubled, there was an increase in fresh weight of fruits. This is in accordance with the findings of <span class="citation" data-cites="dainy2015">Dainy (<a href="#ref-dainy2015" role="doc-biblioref">2015</a>)</span> who also reported a progressive increment in the yield characters in yard long bean as the levels of biochar was enhanced from 10 to 30 t ha<span class="math inline">\(^{-1}\)</span> when applied along with the recommended dose of fertilizers. Similar reports of increased yield with the incorporation of biochar and RDF were also reported by <span class="citation" data-cites="punnoose2015thesis">Punnoose (<a href="#ref-punnoose2015thesis" role="doc-biblioref">2015</a>)</span> in amaranthus and <span class="citation" data-cites="hashmi2019">Hashmi et al. (<a href="#ref-hashmi2019" role="doc-biblioref">2019</a>)</span> in <em>Pisum sativum</em> L. In the case of fruit yield ha<span class="math inline">\(^{-1}\)</span>, the application of tender coconut husk biochar had significantly improved the yield per hectare in okra. Higher fruit yield per hectare was observed for the treatment t4 (<span class="math inline">\(15.71\ \text{t}\)</span>) and was on par with t3 (<span class="math inline">\(14.07\ \text{t}\)</span>). The control plants (t9) could only produce <span class="math inline">\(7.65\ \text{t ha}^{-1}\)</span>. Overall, there was a yield increase of 69 per cent in t4 compared to t9. The lower yield in t9 might be due to the leaching loss of nutrients. There was 44 mm rainfall during the growth period of okra at Onattukara which might have aggravated the leaching loss in the sandy loam soils of Onattukara. <span class="citation" data-cites="nagula2017">Nagula (<a href="#ref-nagula2017" role="doc-biblioref">2017</a>)</span> had also recommended the application of biochar (<span class="math inline">\(@\)</span> 10 kg ha<span class="math inline">\(^{-1}\)</span>) along with RDN for higher yield in banana. The harvest index was also significantly influenced by the treatments. The treatment t3 recorded a higher harvest index of <span class="math inline">\(0.81\)</span> and was found to be on a par with the treatments t4 (<span class="math inline">\(0.81\)</span>), t2 (<span class="math inline">\(0.79\)</span>), t1 (<span class="math inline">\(0.79\)</span>) and t8 (<span class="math inline">\(0.77\)</span>). Thus, biochar as a soil conditioner along with FYM and full recommended dose of fertilizers was effective for okra in the sandy loam soils of Onattukara.</p>
</section>
<section id="nutrient-uptake-1" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="nutrient-uptake-1"><span class="header-section-number">4.2</span> Nutrient uptake</h3>
<p>The N uptake in okra was significantly improved due to the treatments. Among the treatments, the highest N uptake was recorded by the treatment t4 (<span class="math inline">\(101.35\ \text{kg ha}^{-1}\)</span>) and was found to be on a par with t3 (<span class="math inline">\(95.93\ \text{kg ha}^{-1}\)</span>), t2 (<span class="math inline">\(92.90\ \text{kg ha}^{-1}\)</span>), t6 (<span class="math inline">\(92.70\ \text{kg ha}^{-1}\)</span>) and t5 (<span class="math inline">\(91.93\ \text{kg ha}^{-1}\)</span>). Lower N uptake was recorded in t9. There was an increase of 30.14 percent in the N uptake (t4) compared to control (t9). This might be due to the adsorbing capacity of biochar applied as soil conditioner. The higher CEC for biochar might have helped in retaining N in the sandy loam soils of Onattukara. The full RDN along with FYM (5 t ha<span class="math inline">\(^{-1}\)</span>), combined with the adsorbing property of biochar might have contributed to a higher status of available N in soil and led to an increased uptake of N by okra. <span class="citation" data-cites="dainy2015">Dainy (<a href="#ref-dainy2015" role="doc-biblioref">2015</a>)</span> had earlier reported that the total N uptake in yard long bean was found to increase from <span class="math inline">\(51.19\ \text{kg ha}^{-1}\)</span> to <span class="math inline">\(105.50\ \text{kg ha}^{-1}\)</span> due to the application of biochar, PGPR and full recommended dose of nutrients. <span class="citation" data-cites="jabin2022">Jabin (<a href="#ref-jabin2022" role="doc-biblioref">2022</a>)</span> had also reported that total N uptake was higher in ginger when treated with paddy husk biochar (30 t ha<span class="math inline">\(^{-1}\)</span>) along with full dose of fertilizers in sandy soils. Similarly, <span class="citation" data-cites="nigussie2012">Nigussie et al. (<a href="#ref-nigussie2012" role="doc-biblioref">2012</a>)</span> had also reported a higher N uptake in lettuces grown in soils conditioned with 10 t ha<span class="math inline">\(^{-1}\)</span> biochar suggesting the prospects of biochar to raise fertilizer use efficiency in soils where N loss is high.</p>
<p>A significant difference was observed in P uptake among the treatments. Higher P uptake was observed for t7 (<span class="math inline">\(24.76\ \text{kg ha}^{-1}\)</span>) and was on a par with t8 (<span class="math inline">\(23.73\ \text{kg ha}^{-1}\)</span>), t6 (<span class="math inline">\(22.57\ \text{kg ha}^{-1}\)</span>), t5 (<span class="math inline">\(19.98\ \text{kg ha}^{-1}\)</span>) and t3 (<span class="math inline">\(19.60\ \text{kg ha}^{-1}\)</span>). This increase in P uptake might be due to the higher quantity of available P in soil which is evident from the soil samples collected after the harvest of okra (<a href="#tbl-tbl6" class="quarto-xref">Table&nbsp;6</a>). In acidic soils, the solubility of P and its uptake by plants depends mainly on the formation of Al and Fe-phosphates in soil. When biochar is applied to acidic soil condition, it raises the soil pH. There is a reduction in the P binding to Fe and Al oxides, thus making P available in soil. Similar reports of improved P availability in acid soils due to supplementation of biochar was observed by <span class="citation" data-cites="chintala2014">Chintala et al. (<a href="#ref-chintala2014" role="doc-biblioref">2014</a>)</span> and <span class="citation" data-cites="zhang2016">H. Zhang et al. (<a href="#ref-zhang2016" role="doc-biblioref">2016</a>)</span>. On the contrary, <span class="citation" data-cites="dainy2015">Dainy (<a href="#ref-dainy2015" role="doc-biblioref">2015</a>)</span> and <span class="citation" data-cites="jabin2022">Jabin (<a href="#ref-jabin2022" role="doc-biblioref">2022</a>)</span> had reported a higher P uptake in yard long bean and ginger, treated with biochar along with NPK as per <span class="citation" data-cites="kau2016">KAU POP (<a href="#ref-kau2016" role="doc-biblioref">2016</a>)</span>. The uptake of K was not significantly influenced by the treatments.</p>
<p>Significant effect for Ca uptake was observed in okra (<a href="#tbl-tbl4" class="quarto-xref">Table&nbsp;4</a>). The highest Ca uptake was recorded by the treatment t6 (<span class="math inline">\(64.94\ \text{kg ha}^{-1}\)</span>) and was noticed to be on a par with treatment t3 (<span class="math inline">\(59.72\ \text{kg ha}^{-1}\)</span>), t7 (<span class="math inline">\(59.38\ \text{kg ha}^{-1}\)</span>) and t4 (<span class="math inline">\(58.61\ \text{kg ha}^{-1}\)</span>). Lower Ca uptake was recorded by the treatment t9 (KAU POP). There was an overall increase of calcium uptake by 44.96% in t6 compared to the control t9. The application of biochar along with liming prior to planting okra was found to improve the availability of calcium in soil which might have led to an increased plant uptake. Earlier, <span class="citation" data-cites="sombroek1993">Sombroek, Nachtergaele, and Hebel (<a href="#ref-sombroek1993" role="doc-biblioref">1993</a>)</span> had also reported increased calcium availability for plant growth after the application of biochar due to the higher surface area, negative surface charge and charge density. Moreover, calcium in biochar may exchange Al ions present on the soil organic matter and enhance the availability of calcium for plants thus, guiding it to an increased calcium uptake by the plants <span class="citation" data-cites="novak2009">(<a href="#ref-novak2009" role="doc-biblioref">Novak et al. 2009</a>)</span>. <span class="citation" data-cites="dainy2015">Dainy (<a href="#ref-dainy2015" role="doc-biblioref">2015</a>)</span> had also reported higher Ca uptake in yard long bean due to the application of biochar. In sandy soils, <span class="citation" data-cites="jabin2022">Jabin (<a href="#ref-jabin2022" role="doc-biblioref">2022</a>)</span> also observed a higher calcium uptake in ginger.</p>
<p>The uptake of Mg was observed to be significant (<a href="#tbl-tbl4" class="quarto-xref">Table&nbsp;4</a>). The treatment t4 resulted in higher Mg uptake (<span class="math inline">\(20.47\ \text{kg ha}^{-1}\)</span>) by okra and was noticed to be on a par with the treatment t3 (<span class="math inline">\(19.84\ \text{kg ha}^{-1}\)</span>), t6 (<span class="math inline">\(19.61\ \text{kg ha}^{-1}\)</span>) and t8 (<span class="math inline">\(19.60\ \text{kg ha}^{-1}\)</span>). The Mg in soil increases with increase in soil pH. There was an increment in soil pH from the initial value of 5.38 (<a href="#tbl-tbl1" class="quarto-xref">Table&nbsp;1</a>) to 5.87 (<a href="#tbl-tbl5" class="quarto-xref">Table&nbsp;5</a>) due to application of biochar in combination with the effect of liming. This might have improved the exchangeable magnesium in soil which has resulted in an increased magnesium uptake in okra. <span class="citation" data-cites="jabin2022">Jabin (<a href="#ref-jabin2022" role="doc-biblioref">2022</a>)</span> has also reported an increased magnesium uptake in ginger due to application of biochar. Tender coconut husk biochar had 0.13 percent magnesium <span class="citation" data-cites="vikram2024">(<a href="#ref-vikram2024" role="doc-biblioref">Vikram et al. 2024</a>)</span>. This might have contributed to the higher magnesium content in t4. <span class="citation" data-cites="dainy2015">Dainy (<a href="#ref-dainy2015" role="doc-biblioref">2015</a>)</span> had also reported an increase in total Mg uptake in yard long bean when biochar (@ 20 t ha<span class="math inline">\(^{-1}\)</span>) was applied with RDN. The uptake of sulphur was not significantly influenced by the treatments.</p>
<p>Copper uptake was found to be significant (<a href="#tbl-tbl4" class="quarto-xref">Table&nbsp;4</a>) for the treatments. Higher copper uptake in okra was observed for the treatment t1 (<span class="math inline">\(1.82\ \text{kg ha}^{-1}\)</span>) and was found to be on a par with the treatment t3 (<span class="math inline">\(1.73\ \text{kg ha}^{-1}\)</span>). There was an increase in copper content in soil from <span class="math inline">\(1.31\ \text{mg kg}^{-1}\)</span> (<a href="#tbl-tbl1" class="quarto-xref">Table&nbsp;1</a>) to <span class="math inline">\(1.45\ \text{mg kg}^{-1}\)</span> (<a href="#tbl-tbl7" class="quarto-xref">Table&nbsp;7</a>) due to the application of biochar. This might have contributed to the increased uptake of copper in okra. Similar reports of increased copper uptake were noticed in yard long beans by <span class="citation" data-cites="dainy2015">Dainy (<a href="#ref-dainy2015" role="doc-biblioref">2015</a>)</span> and in rice by <span class="citation" data-cites="salvacion2020">Salvacion and Pangga (<a href="#ref-salvacion2020" role="doc-biblioref">2020</a>)</span> due to the application of biochar.</p>
<p>The uptake of zinc was not significantly influenced by the treatments. The uptake of iron in okra was found to be significant (<a href="#tbl-tbl4" class="quarto-xref">Table&nbsp;4</a>). Higher iron uptake was observed for t6 (<span class="math inline">\(0.96\ \text{kg ha}^{-1}\)</span>) and was perceived to be on a par with treatment t1 (<span class="math inline">\(0.88\ \text{kg ha}^{-1}\)</span>) and t3 (<span class="math inline">\(0.82\ \text{kg ha}^{-1}\)</span>). The biochar produced from tender coconut husk contains <span class="math inline">\(107.58\ \text{mg kg}^{-1}\)</span> of iron <span class="citation" data-cites="vikram2024">(<a href="#ref-vikram2024" role="doc-biblioref">Vikram et al. 2024</a>)</span>, and hence its application as a soil conditioner had increased the soil iron content. The initial soil available iron was <span class="math inline">\(14.74\ \text{mg kg}^{-1}\)</span> (<a href="#tbl-tbl1" class="quarto-xref">Table&nbsp;1</a>) and was increased to <span class="math inline">\(15.53\ \text{mg kg}^{-1}\)</span> (t6 – <a href="#tbl-tbl7" class="quarto-xref">Table&nbsp;7</a>) due to the application of biochar. This might be the reason for the increased availability of iron in soil which might have contributed to the increased iron uptake in t6 treatment. Similar report of increased iron uptake in yard long bean was observed by <span class="citation" data-cites="dainy2015">Dainy (<a href="#ref-dainy2015" role="doc-biblioref">2015</a>)</span>.</p>
<p>The uptake of boron was not significantly influenced by the treatments. The uptake of manganese was found to be significantly influenced by the treatments (<a href="#tbl-tbl4" class="quarto-xref">Table&nbsp;4</a>). Among the treatments, the highest uptake of manganese was recorded by the treatment t8 (<span class="math inline">\(1.69\ \text{kg ha}^{-1}\)</span>) and was observed to be on a par with treatment t7 (<span class="math inline">\(1.68\ \text{kg ha}^{-1}\)</span>), t4 (<span class="math inline">\(1.67\ \text{kg ha}^{-1}\)</span>), t6 (<span class="math inline">\(1.61\ \text{kg ha}^{-1}\)</span>) and t2 (<span class="math inline">\(1.46\ \text{kg ha}^{-1}\)</span>). The application of biochar had slightly improved the soil available manganese. This might have improved the plant uptake of manganese in okra. Earlier, <span class="citation" data-cites="dainy2015">Dainy (<a href="#ref-dainy2015" role="doc-biblioref">2015</a>)</span> had also reported the increase in total uptake of manganese from <span class="math inline">\(559.93\)</span> to <span class="math inline">\(1140.50\ \text{g ha}^{-1}\)</span> due to application of biochar in yard long bean.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="soil-attributes" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="soil-attributes"><span class="header-section-number">5</span> Soil attributes</h2>
<p>The soil water holding capacity after cultivation of okra was significantly modified due to the treatments. The initial water holding capacity of the soil from the experimental area (<a href="#tbl-tbl1" class="quarto-xref">Table&nbsp;1</a>) was <span class="math inline">\(10.47\%\)</span>. The treatment t4 recorded a significantly higher WHC (<span class="math inline">\(33.87\%\)</span>) and was found on a par with t8 (<span class="math inline">\(33.02\%\)</span>), t3 (<span class="math inline">\(32.73\%\)</span>), t2 (<span class="math inline">\(32.65\%\)</span>) and t7 (<span class="math inline">\(32.61\%\)</span>). An increase of <span class="math inline">\(20.68\%\)</span> in water holding capacity was observed in t4 (compared to control). An overall increase of <span class="math inline">\(105.55\%\)</span> of WHC could be obtained due to application of biochar in the sandy loam soils of Onattukara. The initial analysis of tender coconut husk biochar had revealed that it had a water holding capacity of <span class="math inline">\(232.34\%\)</span>. This biochar when applied to soil reduces the bulk density of soil and is the reason for the higher water holding capacity of the soil. There was <span class="math inline">\(57.92\%\)</span> increase in WHC with the application of biochar along with NPK as per POP recommendation <span class="citation" data-cites="dainy2015">(<a href="#ref-dainy2015" role="doc-biblioref">Dainy 2015</a>)</span>. <span class="citation" data-cites="wang2019">Wang et al. (<a href="#ref-wang2019" role="doc-biblioref">2019</a>)</span> has also reported that biochar can temporarily increase the field capacity due to their higher pore volume in a coarse textured soil.</p>
<p>The bulk density of soil was found to be significantly reduced by the treatments. The initial bulk density of the soil from the experimental area was <span class="math inline">\(1.61\ \text{Mg m}^{-3}\)</span>. In general, biochar had significantly reduced the soil’s bulk density. KAU 2016 (t9) recorded the highest bulk density (<span class="math inline">\(1.30\ \text{Mg m}^{-3}\)</span>) in soil and the lowest was recorded for the treatment t8 (<span class="math inline">\(1.21\ \text{Mg m}^{-3}\)</span>). Overall, there was a reduction in bulk density by <span class="math inline">\(28.37\%\)</span> compared to the initial value indicating the potential for increased water holding capacity. There are several reports of decreased bulk density with application of biochar <span class="citation" data-cites="laird2010 jones2010 chen2011 mankasingh2011 zhang2012">(<a href="#ref-laird2010" role="doc-biblioref">Laird et al. 2010</a>; <a href="#ref-jones2010" role="doc-biblioref">Jones, Haynes, and Phillips 2010</a>; <a href="#ref-chen2011" role="doc-biblioref">Chen et al. 2011</a>; <a href="#ref-mankasingh2011" role="doc-biblioref">Mankasingh, Choi, and Ragnarsdottir 2011</a>; <a href="#ref-zhang2012" role="doc-biblioref">A. Zhang et al. 2012</a>)</span>. <span class="citation" data-cites="dainy2015">Dainy (<a href="#ref-dainy2015" role="doc-biblioref">2015</a>)</span> had also reported in yard long bean that the application of biochar had lowered the bulk density of soil. The pH, electrical conductivity and CEC in soil after the experiment was not significantly influenced by the treatments.</p>
<p>The organic carbon content of the soil after the experiment was significantly governed by the treatments. Higher organic carbon was noticed for t4 (<span class="math inline">\(1.29\%\)</span>) and was on par with t8 (<span class="math inline">\(1.26\%\)</span>), t3 (<span class="math inline">\(1.25\%\)</span>), t2 (<span class="math inline">\(1.23\%\)</span>), t7 (<span class="math inline">\(1.23\%\)</span>), t1 (<span class="math inline">\(1.19\%\)</span>) and t6 (<span class="math inline">\(1.17\%\)</span>). The control treatment (t9) recorded the lowest organic carbon content (<span class="math inline">\(0.96\%\)</span>). There was an overall increase of <span class="math inline">\(29.33\%\)</span> in t4 compared to KAU (2016) due to the application of biochar. The initial organic carbon content in soil before the experiment was <span class="math inline">\(0.53\%\)</span> (<a href="#tbl-tbl1" class="quarto-xref">Table&nbsp;1</a>). Biochar produced from tender coconut husk had a total organic carbon content of <span class="math inline">\(48.14\%\)</span> <span class="citation" data-cites="vikram2024">(<a href="#ref-vikram2024" role="doc-biblioref">Vikram et al. 2024</a>)</span>, and application of this might have helped in the increased carbon content in biochar applied plants. In amaranthus, <span class="citation" data-cites="punnoose2015article">Punnoose and Anitha (<a href="#ref-punnoose2015article" role="doc-biblioref">2015</a>)</span> had also reported higher organic carbon content in biochar applied plants.</p>
<p>There were significant effects on available N in soil. Higher available N was observed for t4 (<span class="math inline">\(209.07\ \text{kg ha}^{-1}\)</span>) and was on a par with the treatments t3, t7 and t8 with <span class="math inline">\(196.52\ \text{kg ha}^{-1}\)</span>. This might be due to the increased retention of nitrogen in soil due to the application of biochar. <span class="citation" data-cites="punnoose2015thesis">Punnoose (<a href="#ref-punnoose2015thesis" role="doc-biblioref">2015</a>)</span> had also reported an increased nutrient content in biochar applied soils. The control (t9) recorded an available N content of <span class="math inline">\(183.98\ \text{kg ha}^{-1}\)</span>. There was <span class="math inline">\(44\ \text{mm}\)</span> of rain during the crop period which might have leached out the available N in soil leading to a comparatively lesser available N in soil. The lowest available N was recorded for t5 and t6 with <span class="math inline">\(163.07\ \text{kg ha}^{-1}\)</span>. The lower dose of fertilizer without the application of FYM might have led to the lowest available N in soil.</p>
</section>
<section id="conclusion" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">6</span> Conclusion</h2>
<p>It could be concluded that the rate of biochar as a soil conditioner for okra in the sandy loam soils of Onattukara is standardized as <span class="math inline">\(10\ \text{t ha}^{-1}\)</span>. The soil application of biochar at the rate of <span class="math inline">\(10\ \text{t ha}^{-1}\)</span> along with <span class="math inline">\(5\ \text{t ha}^{-1}\)</span> FYM and <span class="math inline">\(100\%\)</span> RDF could be recommended for enhancing yield, nutrient uptake and soil fertility in okra.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Acknowledgments">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Acknowledgments
</div>
</div>
<div class="callout-body-container callout-body">
<p>The authors are grateful to the support and encouragement provided by Kerala Agricultural University throughout the conduct of the research work.</p>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<!-- References will be rendered here -->
<div id="ref-black1965" class="csl-entry" role="listitem">
Black, C. A. 1965. <em>Methods of Soil Analysis. Part i</em>. Madison, Wisconsin, USA: American Society of Agronomy.
</div>
<div id="ref-chen2011" class="csl-entry" role="listitem">
Chen, H. X., Z. L. Du, W. Guo, and Q. Z. Zhang. 2011. <span>“Effects of Biochar Amendment on Cropland Soil Bulk Density, Cation Exchange Capacity, and Particulate Organic Matter Content in the North China Plain.”</span> <em>Journal of Applied Ecology</em> 22: 2930–34.
</div>
<div id="ref-chesnin1950" class="csl-entry" role="listitem">
Chesnin, L., and C. H. Yien. 1950. <span>“Turbidimetric Determination of Available Sulphates.”</span> <em>Soil Science Society of America Proceedings</em> 15: 149–51.
</div>
<div id="ref-chintala2014" class="csl-entry" role="listitem">
Chintala, R., J. Mollinedo, T. E. Schumacher, D. D. Malo, and J. L. Julson. 2014. <span>“Effect of Biochar on Chemical Properties of Acidic Soil.”</span> <em>Archives of Agronomy and Soil Science</em> 60 (3): 393–404.
</div>
<div id="ref-dainy2015" class="csl-entry" role="listitem">
Dainy, M. M. S. 2015. <span>“Investigation on the Efficacy of Biochar from Tender Coconut Husk for Enhance Crop Production.”</span> PhD thesis, Kerala Agricultural University, Thrissur.
</div>
<div id="ref-hashmi2019" class="csl-entry" role="listitem">
Hashmi, S., U. Younis, S. Danish, and T. M. Munir. 2019. <span>“Pongamia Pinnata l. Leaves Biochar Increased Growth and Pigment Syntheses in Pisum Sativum l. Exposed to Nutritional Stress.”</span> <em>Agriculture</em> 9 (7): 1–13.
</div>
<div id="ref-hesse1971" class="csl-entry" role="listitem">
Hesse, P. R. 1971. <em>A Textbook of Soil Chemical Analysis</em>. London: William Clowes; Sons.
</div>
<div id="ref-jabin2022" class="csl-entry" role="listitem">
Jabin, N. P. P. 2022. <span>“Biochar for Carbon Sequestration, Soil Health and Crop Productivity.”</span> PhD thesis, Kerala Agricultural University, Thrissur.
</div>
<div id="ref-jackson1958" class="csl-entry" role="listitem">
Jackson, M. L. 1958. <em>Soil Chemical Analysis</em>. New Delhi, India: Prentice Hall of India Pvt. Ltd.
</div>
<div id="ref-jackson1973" class="csl-entry" role="listitem">
———. 1973. <em>Soil Chemical Analysis (2nd Ed.)</em>. New Delhi, India: Prentice Hall of India Pvt. Ltd.
</div>
<div id="ref-jones2010" class="csl-entry" role="listitem">
Jones, B. E. H., R. J. Haynes, and I. R. Phillips. 2010. <span>“Effect of Amendment of Bauxite Processing Sand with Organic Materials on Its Chemical, Physical and Microbial Properties.”</span> <em>Journal of Environmental Management</em> 91 (11): 2281–88.
</div>
<div id="ref-kau2016" class="csl-entry" role="listitem">
KAU POP. 2016. <em>Package of Practices Recommendations: Crops (15th Ed.)</em>. Thrissur: Kerala Agricultural University.
</div>
<div id="ref-laird2010" class="csl-entry" role="listitem">
Laird, D. A., P. Fleming, D. D. Davis, R. Horton, B. Q. Wang, and D. L. Karlen. 2010. <span>“Impact of Biochar Amendments on the Quality of a Typical Midwestern Agricultural Soil.”</span> <em>Geoderma</em> 158: 443–49.
</div>
<div id="ref-lindsay1978" class="csl-entry" role="listitem">
Lindsay, W. L., and W. A. Norvell. 1978. <span>“Development of DTPA Micronutrients Soil Test for Zinc, Iron, Manganese and Copper.”</span> <em>Soil Science Society of America Journal</em> 42: 421–28.
</div>
<div id="ref-mankasingh2011" class="csl-entry" role="listitem">
Mankasingh, U., P. C. Choi, and V. Ragnarsdottir. 2011. <span>“Biochar Application in a Tropical, Agricultural Region: A Plot Scale Study in Tamil Nadu, India.”</span> <em>Applied Geochemistry</em> 26 (8): 1594–97.
</div>
<div id="ref-mohammed2025raisins" class="csl-entry" role="listitem">
Mohammed, H. M., J. Chandran, and P. P. Gopinath. 2025. <span>“RAISINS: Integrating r and AI for Agricultural Data Analysis.”</span> <em>Journal of Sustainable Technology in Agriculture</em> 1 (1). <a href="https://doi.org/10.5281/zenodo.15622128">https://doi.org/10.5281/zenodo.15622128</a>.
</div>
<div id="ref-nagula2017" class="csl-entry" role="listitem">
Nagula, S. 2017. <span>“Technology Refinement for Biochar Production and Evaluation of Its Effects on Soil Health and Crop Productivity.”</span> PhD thesis, Kerala Agricultural University, Thrissur.
</div>
<div id="ref-nigussie2012" class="csl-entry" role="listitem">
Nigussie, A., E. Kissi, M. Misganaw, and G. Ambaw. 2012. <span>“Effect of Biochar Application on Soil Properties and Nutrient Uptake of Lettuces (Lactuca Sativa) Grown in Chromium Polluted Soils.”</span> <em>American-Eurasian Journal of Agricultural and Environmental Sciences</em> 12 (3): 369–76.
</div>
<div id="ref-novak2009" class="csl-entry" role="listitem">
Novak, J. M., W. J. Busscher, D. L. Laird, M. Ahmedna, D. W. Watts, and M. A. Niandou. 2009. <span>“Impact of Biochar Amendment on Fertility of a Southeastern Coastal Plain Soil.”</span> <em>Soil Science</em> 174 (2): 105–12.
</div>
<div id="ref-punnoose2015thesis" class="csl-entry" role="listitem">
Punnoose, A. 2015. <span>“Production, Characterisation and Quality Assessment of Biochar.”</span> Master’s thesis, Kerala Agricultural University, Thrissur.
</div>
<div id="ref-punnoose2015article" class="csl-entry" role="listitem">
Punnoose, A., and S. Anitha. 2015. <span>“Production and Characterisation of Biochar from Different Organic Materials.”</span> <em>Journal of Tropical Agriculture</em> 53 (2): 191–96.
</div>
<div id="ref-salvacion2020" class="csl-entry" role="listitem">
Salvacion, S. O., and G. V. Pangga. 2020. <span>“Response of Lowland Rice Grown in Mine-Contaminated Soil with Coconut Husk and Cattle Manure Biochars.”</span> <em>Rice-Based Biosystems Journal</em> 7: 1–12.
</div>
<div id="ref-singh2014" class="csl-entry" role="listitem">
Singh, R. P., and D. G. Kaskaoutis. 2014. <span>“Crop Residue Burning: A Threat to South Asian Air Quality.”</span> <em>EOS Transactions</em> 95 (37): 333–40.
</div>
<div id="ref-sombroek1993" class="csl-entry" role="listitem">
Sombroek, W. G., F. O. Nachtergaele, and A. Hebel. 1993. <span>“Amounts, Dynamics and Sequestering of Carbon in Tropical and Subtropical Soils.”</span> <em>Journal of Human Environment Research and Management</em> 22 (7): 417–26.
</div>
<div id="ref-subbiah1956" class="csl-entry" role="listitem">
Subbiah, B. V., and G. I. Asija. 1956. <span>“A Rapid Procedure for Estimation of Available Nitrogen in Soil.”</span> <em>Current Science</em> 25: 258–60.
</div>
<div id="ref-vikram2024" class="csl-entry" role="listitem">
Vikram, K., A. Jayapal, S. P. Pillai, S. R. Isaac, and V. Mini. 2024. <span>“Characterization of Biochar Produced from Different Agro-Wastes.”</span> <em>Journal of Crop and Weed</em> 20 (1): 12–20.
</div>
<div id="ref-walkley1934" class="csl-entry" role="listitem">
Walkley, A., and T. A. Black. 1934. <span>“An Examination of Degtjareff Method for Determining Soil Organic Matter and Proposed Modification of the Chromic Acid Titration Method.”</span> <em>Soil Science</em> 37: 29–38.
</div>
<div id="ref-wang2019" class="csl-entry" role="listitem">
Wang, D., C. Li, S. J. Parikh, and K. M. Scow. 2019. <span>“Impact of Biochar on Water Retention of Two Agricultural Soils – a Multiscale Analysis.”</span> <em>Geoderma</em> 340: 185–91.
</div>
<div id="ref-zhang2012" class="csl-entry" role="listitem">
Zhang, A., R. Bian, G. Pan, L. Cui, Q. Hussain, L. Li, J. Zheng, et al. 2012. <span>“Effects of Biochar Amendment on Soil Quality, Crop Yield and Greenhouse Gas Emission in a Chinese Rice Paddy: A Field Study of Two Consecutive Rice Growing Cycles.”</span> <em>Field Crops Research</em> 127: 153–60.
</div>
<div id="ref-zhang2016" class="csl-entry" role="listitem">
Zhang, H., C. Chen, E. M. Gray, S. E. Boyd, H. Yang, and D. Zhang. 2016. <span>“Roles of Biochar in Improving Phosphorus Availability in Soils: A Phosphate Adsorbent and a Source of Available Phosphorus.”</span> <em>Geoderma</em> 276: 1–6.
</div>
</div>
<div style="page-break-after: always;"></div>
<div class="callout callout-style-default callout-tip callout-titled" title="Technical Details">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Technical Details
</div>
</div>
<div class="callout-body-container callout-body">
<p>The statistical analysis of the data was done by applying the technique of analysis of variance (ANOVA) for Randomised Block Design and was done using RAISINS <span class="citation" data-cites="mohammed2025raisins">(<a href="#ref-mohammed2025raisins" role="doc-biblioref">Mohammed, Chandran, and Gopinath 2025</a>)</span> online statistical analysis platform.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Publication &amp; Reviewer Details">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Publication &amp; Reviewer Details
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Publication Information</strong></p>
<ul>
<li><strong>Submitted:</strong> <em>15 June 2025</em><br>
</li>
<li><strong>Accepted:</strong> <em>20 June 2025</em><br>
</li>
<li><strong>Published (Online):</strong> <em>20 June 2025</em></li>
</ul>
<hr>
<p><strong>Reviewer Information</strong></p>
<ul>
<li><p><strong>Reviewer 1:</strong><br>
<strong>Dr.Gayathri Karthikeyan P</strong><br>
<em>Department of Agronomy</em><br>
<em>College of Agriculture, Vellayani</em><br>
<em>Kerala Agricultural University</em></p></li>
<li><p><strong>Reviewer 2:</strong><br>
<em>Anonymous</em></p></li>
</ul>
</div>
</div>



</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>RDF=Recommended Dose of Fertilizer<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>FYM=Farm Yard Manure<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Ex. stands for Exchangeable<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/www\.jostapubs\.com\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Published by PAPAYA publishing <a href="https://www.statoberry.com/papaya"><img src="../..\images/papayalogo.png" class="img-fluid" style="width: auto; height: 25px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>   
    <div class="nav-footer-center">
<p><a href="https://www.statoberry.com/papaya"><img src="../..\images/Josta.png" class="img-fluid" style="height: 90px;"></a></p>
</div>
    <div class="nav-footer-right">
<p>Licenced under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC-BY-NC-ND 4.0 Int License</a> <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img src="../..\images/cclogo.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a> Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>